# Generated by Django 2.2 on 2022-01-28 08:40

import api.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=128, serialize=False, verbose_name='Password')),
                ('E_Mail', models.EmailField(editable=False, max_length=50, unique=True, verbose_name='e-mail')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Famale'), ('secret', 'Secret')], default='secret', max_length=6, verbose_name='Sex')),
                ('BirthDay', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('Profile_Pic', models.ImageField(default='default/user.jpg', upload_to=api.models.user_directory_path, verbose_name='Avatar')),
                ('QQ', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.'), django.core.validators.MinLengthValidator(5, message='Too short')], verbose_name='QQ Number')),
                ('Telephone', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^[+]?[0-9]*$', 'Only 0-9 are allowed.'), django.core.validators.MinLengthValidator(10, message='Too short')], verbose_name='Telephone')),
                ('Describe', models.CharField(blank=True, max_length=128, null=True, verbose_name='Describe')),
                ('Ctime', models.DateTimeField(auto_now_add=True, verbose_name='Register Time')),
                ('Last_Login', models.DateTimeField(default=datetime.datetime.now)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('Secret', models.CharField(blank=True, max_length=40, null=True, verbose_name='Secret_Field')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='User token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='expiration time')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
