# Generated by Django 2.2 on 2022-01-28 16:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=api.models.upload_directory_path, verbose_name='Avatar')),
            ],
        ),
    ]
